another try

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -408,6 +408,19 @@ jobs:
 #            export API_URL="http://${BACKEND_IP}:3030"
 #            echo ${API_URL}
       - run:
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com/"
+            echo ${URL}
+            if curl -s ${URL} | grep "Welcome"
+              then
+                echo "Success"
+              else
+                echo "Fail"
+                exit 1
+              fi
+      - run:
           name: Backend smoke test.
           command: |
             # your code here
@@ -422,20 +435,7 @@ jobs:
               echo "Fail"
               exit 1
             fi
-      - run:
-          name: Frontend smoke test.
-          command: |
-            # your code here
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com/"
-            echo ${URL}
-            if curl -s ${URL} | grep "Welcome"
-              then
-                echo "Success"
-              else
-                echo "Fail"
-                exit 1
-              fi
-      # Here's where you will add some code to rollback on failure  
+      # Here's where you will add some code to rollback on failure
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
       - revert-migrations:
