test roll back of migrations again and again and again and again and again

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -35,16 +35,16 @@ commands:
             cd ~/project/backend
             npm install
             #  Add revert code here. You can find this in the Getting Started section.
-            curl -H "token: 568fab66-432b-4408-b72e-b57e1c19f236" \
-            --request GET https://api.memstash.io/values/<<parameters.workflow_id>>
-            SUCCESS = 'failed'
-            if $SUCCESS=='failed';
-            then
-              # revert the migrations
-              cd backend
-              npm run migrations:revert
-            fi
+            # revert the migrations
+            cd backend
+            npm run migrations:revert
+#            fi
 #            exit 1
+#            curl -H "token: 568fab66-432b-4408-b72e-b57e1c19f236" \
+#            --request GET https://api.memstash.io/values/<<parameters.workflow_id>>
+#            SUCCESS = 'failed'
+#            if $SUCCESS=='failed';
+#            then
 
 jobs:
   build-frontend:
@@ -256,20 +256,9 @@ jobs:
           command: |
             # Your code here
             cd ~/project/backend
-            echo ENVIROMENT="production" > ".env"
-            echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> ".env"
-            echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> ".env"
-            echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> ".env"
-            echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> ".env"
-            echo TYPEORM_HOST=$TYPEORM_HOST >> ".env"
-            echo TYPEORM_PORT=$TYPEORM_PORT >> ".env"
-            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> ".env"
-            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> ".env"
-            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> ".env"
             npm install
             npm run migrations >> migrations.txt
             cat migrations.txt
-            cat .env
             exit 1
       - run:
           name: Send migration results to memstash
@@ -277,7 +266,7 @@ jobs:
             # Your code here
             curl -H "Content-Type: text/plain" -H "token: 568fab66-432b-4408-b72e-b57e1c19f236" \
               --request PUT --data "0" https://api.memstash.io/values/migration-results
-            exit 1
+#            exit 1
      # Here's where you will add some code to rollback on failure      
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
