some more changes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -368,14 +368,15 @@ jobs:
             echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
             echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
             echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
+            cat backend/.env
       - run:
           name: Deploy backend
           command: |
             # your code here
             cd .circleci/ansible
-            BACKEND_IP=`cat inventory.txt | head -2 | tail -1`
+            BACKEND_IP=`cat project/.circleci/ansible/inventory.txt | head -2 | tail -1`
             echo "BACKEND_IP: ${BACKEND_IP}"
-            ansible-playbook -i inventory.txt deploy-backend.yml
+            ansible-playbook -i project/.circleci/ansible/inventory.txt deploy-backend.yml
       # Here's where you will add some code to rollback on failure
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
@@ -407,25 +408,25 @@ jobs:
               --filters "Name=tag:project,Values=ds-cicdproj-backend" \
               --output text >> BACKEND_IP
             cat BACKEND_IP
-##            export API_URL="http://${BACKEND_IP}:3030"
-##            echo ${API_URL}
-#      - run:
-#          name: Backend smoke test.
-#          command: |
-#            # your code here
-#            MYIP=$(aws ec2 describe-instances \
-#              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-#              --filters "Name=tag:project,Values=ds-cicdproj-backend" \
-#              --output text)
-#            echo ${MYIP}
-#            echo "curl_target:http://${MYIP}:3030/api/status"
-#            curl "http://${MYIP}:3030/api/status"
-#            if curl -sL --fail "https://${MYIP}:3030/api/status"; then
-#              echo "Success"
-#            else
-#              echo "Fail"
-#            fi
-##            exit 1
+#            export API_URL="http://${BACKEND_IP}:3030"
+#            echo ${API_URL}
+      - run:
+          name: Backend smoke test.
+          command: |
+            # your code here
+            MYIP=$(aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:project,Values=ds-cicdproj-backend" \
+              --output text)
+            echo ${MYIP}
+            echo "curl_target:http://${MYIP}:3030/api/status"
+            curl "http://${MYIP}:3030/api/status"
+            if curl -sL --fail "https://${MYIP}:3030/api/status"; then
+              echo "Success"
+            else
+              echo "Fail"
+            fi
+#            exit 1
       - run:
           name: Frontend smoke test.
           command: |
