some more changes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -416,12 +416,12 @@ jobs:
               --filters "Name=tag:project,Values=ds-cicdproj-backend" \
               --output text)
             echo ${MYIP}
-            if curl -sL --fail "http://${MYIP}:3030/api/status"; then
+            if curl -sL --fail "https://${MYIP}:3030/api/status"; then
               echo "Success"
             else
               echo "Fail"
+              exit 1
             fi
-#            exit 1
       - run:
           name: Frontend smoke test.
           command: |
@@ -432,13 +432,14 @@ jobs:
               then
                 echo "Success"
               else
+                echo "Fail"
                 exit 1
               fi
       # Here's where you will add some code to rollback on failure  
-#      - destroy-environment:
-#          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-#      - revert-migrations:
-#          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
   cloudfront-update:
     docker:
@@ -447,17 +448,20 @@ jobs:
     steps:
       # Checkout code from git
       - checkout
-#      - run:
-#          name: Install dependencies
-#          command: |
-#            # your code here
-#            exit 1
+      - run:
+          name: Install dependencies
+          command: |
+            # your code here
+            yum -y install tar gzip
+            curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
+            yum -y install nodejs
+            exit 1
       - run:
           name: Update cloudfront distribution
           command: |
             # your code here
             aws cloudformation deploy --template-file .circleci/files/cloudfront.yml \
-              --stack-name udapeople-cloudfront --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID}"
+              --stack-name udapeople-cloudfront --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}"
       # Here's where you will add some code to rollback on failure
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
@@ -475,7 +479,7 @@ jobs:
             # your code here
             export OldWorkflowID=$(aws cloudformation list-exports \
               --query "Exports[?Name==\`WorkflowID\`].Value" --no-paginate --output text)
-            export STACKS=["be_${OldWorkflowID", "fe_${OldWorkflowID"] #put the list of stacks here
+            export STACKS=["be_${OldWorkflowID}", "fe_${OldWorkflowID}"] #put the list of stacks here
       - run:
           name: Remove old stacks and files
           command: |
